services:
  mongodb:
    image: mongo:latest
    container_name: comp3123-assignment2-mongodb
    restart: unless-stopped
    networks:
      - backend
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: comp3123-assignment2-backend
    depends_on:
      - mongodb
    networks:
      - backend
    environment:
      - DB_URL=mongodb://mongodb:27017/comp3123-assignment2
    ports:
      - "8089:8089"
    volumes:
      - ./backend:/usr/src/app
    command: node server.js

  frontend:
    build: frontend/.
    container_name: comp3123-assignment2-frontend
    ports:
      - "3001:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3001/api/v1
    depends_on:
      - backend
    networks:
      - backend

  mongo-express:
    image: mongo-express:latest
    restart: unless-stopped
    ports:
      - "8091:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=comp3123-assignment2
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin

volumes:
  mongodbdata:

networks:
  backend:
